export const DOWNLOAD_URL_PLACEHOLDER = "#download";
export const SITE_URL = ""; // Set to the verified Sites URL before release.
export const copy = {
  title: "Blink - 把任意按键变成快捷动作",
  description:
    "Blink 是一款桌面快捷控制工具，将 App、URL、脚本和系统动作绑定到实体按键，一键启动、切换和执行。",
  email: "lixinzhang0703@gmail.com",
  hero: {
    badge: "为你的 Mac，多一点顺手",
    title: ["把常用动作，", "交给一个按键。"],
    description: "将 App、URL、脚本和系统动作绑定到实体键盘。\n一键直达，少一点寻找，多一点专注。",
  },
  scenarios: [
    {
      name: "开发者",
      tag: "BUILD YOUR NEXT IDEA",
      title: "从灵感，到代码。少几个点击。",
      description: "为你的工作流准备一组专属按键。编辑器、终端和开发页面，各就各位。",
      items: [
        ["自定义按键", "VS Code", "打开编辑器", "code"],
        ["自定义按键", "Terminal", "进入终端", "terminal"],
        ["自定义按键", "GitHub", "查看代码仓库", "github"],
        ["自定义按键", "localhost", "打开本地页面", "globe"],
      ],
    },
    {
      name: "电商运营",
      tag: "YOUR DAILY OPERATIONS",
      title: "每天的高频后台，触手可及。",
      description: "不用再找收藏夹，把每天都会打开的工具直接放到键盘上。",
      items: [
        ["你的按键", "店铺后台", "打开店铺页面", "store"],
        ["你的按键", "客服系统", "进入客服工作台", "message"],
        ["你的按键", "ERP / OMS", "打开管理后台", "layout"],
        ["你的按键", "数据看板", "查看经营数据", "chart"],
      ],
    },
    {
      name: "内容与办公",
      tag: "MAKE ROOM FOR FOCUS",
      title: "少找一个窗口，多留一点心流。",
      description: "减少寻找窗口和重复点击，把注意力留给真正的工作。",
      items: [
        ["已绑定按键", "邮箱", "打开收件箱", "mail"],
        ["已绑定按键", "Notion", "进入笔记空间", "file"],
        ["已绑定按键", "ChatGPT", "打开常用应用", "message"],
        ["已绑定按键", "工作文件夹", "打开本地目录", "folder"],
      ],
    },
  ],
  features: [
    ["app", "打开 App", "把常用应用，放到顺手的位置。快速启动，直接进入。", "已实现"],
    ["globe", "打开 URL", "后台、文档、固定网页。常用入口，不必再翻收藏夹。", "已实现"],
    ["terminal", "执行脚本", "运行本地 .sh 脚本，为开发和日常工作少一次重复操作。", "已实现"],
    ["command", "系统快捷操作", "绑定复制、粘贴等快捷键。需授予 macOS 辅助功能权限。", "已实现"],
    ["switch", "快速切换 App", "需要时叫出，结束后收起。让窗口跟上你的节奏。", "即将支持"],
  ],
  steps: [
    ["01", "连接你的键盘", "普通键盘或 Macro Pad，选择系统能够识别的按键。"],
    ["02", "选择一个动作", "在 Blink 中创建 App、URL、脚本或快捷键命令。"],
    ["03", "录制并绑定按键", "为命令录制实体按键，保存绑定。按一下，开始使用。"],
  ],
};

export const labels = {
  brand: "Blink",
  skip: "跳转到正文",
  navFeatures: "功能",
  navScenarios: "使用场景",
  navHow: "如何使用",
  download: "下载 Blink12",
  betaCta: "申请 Blink 内测12",
  learn: "了解 Blink",
  macFirst: "macOS 优先",
  separator: "·",
  early: "早期版本，下载即将开放",
  windowDots: "● ● ●",
  runtime: "Blink Runtime",
  shotTag: "为专注而设计",
  shotCaption: "来自当前 Runtime 的界面截图 · 展示状态为模拟数据",
  physicalKeys: "实体按键，软件定义",
  oneKey: "一个按键，一个动作",
  noFirmware: "无需刷固件",
  scenariosEyebrow: "MADE FOR YOUR EVERYDAY",
  scenariosTitle: "你的工作流，",
  scenariosTitleAccent: "就在键盘上。",
  scenariosDescription: "为每天重复打开的工具，准备一排专属快捷键。",
  scenarioNote: "配置示例 · 每个按键对应一个独立动作",
  exampleStatus: "使用示例",
  toggleEyebrow: "RIGHT HERE. THEN OUT OF THE WAY.",
  soon: "即将支持",
  togglePlatform: "macOS App 切换",
  toggleTitle: "一键叫出，",
  toggleTitleAccent: "再按一次收起。",
  toggleDescription: "为常用 App 设置专属按键。需要时立即呼出，使用结束后一键隐藏。",
  toggleStateNote: "根据应用真实状态决定下一步动作。",
  toggleReleaseNote: "功能开发中，稳定版本确认后开放。",
  toggleExample: "以 ChatGPT 为例",
  toggleDiagram: "行为示意",
  toggleKey: "你的按键",
  toggleFooter: "随叫随到，也懂适时退场。",
  keysEyebrow: "KEY TO APP INTERACTION",
  keysTitle: "按下一个键，",
  keysTitleAccent: "让应用立刻回应。",
  keysDescription:
    "Blink 让一个按键直接对应一个软件结果。打开、切换、收起或触发，都可以变成手边的一个动作。",
  keysNote: "每个画面都是一个独立动作示例；设备需能向系统发送可识别按键。",
  keyboardStoryLabel: "键盘与应用互动故事",
  macroPadAlt: "三键 Macro Pad 与 Blink 软件动作互动示意",
  macroPadCaption: "硬件仅作使用示意，Blink 不依赖特定键盘型号。",
  featuresEyebrow: "SMALL KEY. MORE POSSIBILITIES.",
  featuresTitle: "一个按键，",
  featuresTitleAccent: "可以做更多。",
  featuresDescription: "从打开应用到运行脚本，把重复的点击交给 Blink。",
  firmwareEyebrow: "YOUR KEYBOARD. YOUR RULES.",
  firmwareTitle: "不刷固件，",
  firmwareTitleAccent: "直接定义键盘。",
  firmwareLead: "键盘保持原样。",
  firmwareLeadEnd: "改变的，是你使用它的方式。",
  firmwareDescription:
    "按键定义保存在电脑端。更换动作，只需修改软件配置，无需重新烧录键盘，也不需要为映射安装厂商专用驱动。",
  softwareConfig: "软件侧配置",
  editAnytime: "随时调整动作",
  keyboardTypes: "普通键盘 / Macro Pad",
  firmwareNote: "设备需能向系统发送可识别按键。不同电脑需要各自配置，当前不提供账号同步。",
  howEyebrow: "LESS SETUP. MORE DOING.",
  howTitle: "简单三步，",
  howTitleAccent: "让按键就位。",
  downloadEyebrow: "ONE KEY. YOUR WAY.",
  downloadTitle: "让你的键盘，",
  downloadTitleAccent: "真正为你工作。",
  tagline: "把常用动作，交给一个按键。",
  downloadMac: "下载 Blink for macOS",
  downloadSoon: "即将开放",
  downloadNote: "正在准备首个公开下载版本。",
  contactAuthor: "联系作者",
  mac: "macOS",
  macStatus: "优先支持",
  windows: "Windows",
  windowsStatus: "后续计划",
  footerTagline: "一个按键，一个动作。",
  product: "产品",
  footerDownload: "下载",
  support: "支持",
  emailFeedback: "邮件反馈",
  feedbackLine1: "如果新版本使用中遇到问题，",
  feedbackLine2: "欢迎发送邮件反馈。",
  copyright: "© 2026 Blink",
  footerEnglish: "Designed for your everyday.",
  downloadReady: "macOS 版本现已开放下载",
  homeLabel: "Blink 首页",
  navLabel: "主导航",
  scenarioLabel: "选择使用场景",
  screenshotAlt: "Blink Runtime 中文设置页，展示通用设置、运行状态和帮助反馈",
};

export const labelsEn: Partial<typeof labels> = {
  brand: "Blink",
  skip: "Skip to content",
  navFeatures: "Features",
  navScenarios: "Use cases",
  navHow: "How it works",
  download: "Download Blink",
  betaCta: "Request beta access",
  learn: "Explore Blink",
  macFirst: "macOS first",
  early: "Early release",
  downloadReady: "Downloads are ready",
  physicalKeys: "Physical keys, software-defined",
  oneKey: "One key, one action",
  noFirmware: "No firmware flashing",
  scenariosEyebrow: "MADE FOR YOUR EVERYDAY",
  scenariosTitle: "Your workflow,",
  scenariosTitleAccent: "on your keyboard.",
  scenariosDescription: "Give the tools you open every day their own shortcuts.",
  scenarioNote: "Example configuration · each key maps to one action",
  exampleStatus: "Example",
  keysEyebrow: "KEY TO APP INTERACTION",
  keysTitle: "Press one key,",
  keysTitleAccent: "make an app respond.",
  keysDescription: "Blink turns one key into a direct software result: open, switch, hide, or trigger.",
  keysNote: "Each screen is an independent action example; the device must send a recognizable key.",
  featuresEyebrow: "SMALL KEY. MORE POSSIBILITIES.",
  featuresTitle: "One key,",
  featuresTitleAccent: "more possibilities.",
  featuresDescription: "From opening apps to running scripts, leave repetitive clicks to Blink.",
  firmwareEyebrow: "YOUR KEYBOARD. YOUR RULES.",
  firmwareTitle: "No firmware,",
  firmwareTitleAccent: "just define your keyboard.",
  firmwareLead: "Keep your keyboard as it is.",
  firmwareLeadEnd: "Change how you use it.",
  firmwareDescription: "Key definitions live on your computer. Change actions in software without flashing firmware or installing a vendor driver.",
  softwareConfig: "Software-side configuration",
  editAnytime: "Adjust actions anytime",
  keyboardTypes: "Standard keyboard / Macro Pad",
  howEyebrow: "LESS SETUP. MORE DOING.",
  howTitle: "Three simple steps,",
  howTitleAccent: "and your keys are ready.",
  downloadEyebrow: "ONE KEY. YOUR WAY.",
  downloadTitle: "Make your keyboard,",
  downloadTitleAccent: "work for you.",
  tagline: "Put your everyday actions behind one key.",
  downloadMac: "Download Blink",
  downloadNote: "The latest release is selected automatically for your system.",
  contactAuthor: "Contact the author",
  mac: "macOS",
  macStatus: "Apple Silicon",
  windows: "Windows",
  windowsStatus: "x64",
  footerTagline: "One key, one action.",
  product: "Product",
  footerDownload: "Download",
  support: "Support",
  emailFeedback: "Email feedback",
  feedbackLine1: "If you run into an issue,",
  feedbackLine2: "we would love to hear from you.",
  footerEnglish: "Designed for your everyday.",
  homeLabel: "Blink home",
  navLabel: "Main navigation",
  scenarioLabel: "Choose a use case",
  screenshotAlt: "Blink Runtime settings screen",
};

export const copyEn = {
  ...copy,
  title: "Blink - Turn any key into a shortcut",
  description: "Blink is a desktop shortcut tool that binds apps, URLs, scripts, and system actions to physical keys.",
  hero: {
    badge: "A smoother Mac workflow",
    title: ["Put everyday actions,", "behind one key."],
    description: "Bind apps, URLs, scripts, and system actions to physical keys.\nLess searching, more focus.",
  },
  scenarios: [
    { name: "Developer", tag: "BUILD YOUR NEXT IDEA", title: "From idea to code, with fewer clicks.", description: "Give your editor, terminal, and dev pages their own keys.", items: [["Custom key", "VS Code", "Open editor", "code"], ["Custom key", "Terminal", "Open terminal", "terminal"], ["Custom key", "GitHub", "Open repository", "github"], ["Custom key", "localhost", "Open local page", "globe"]] },
    { name: "Operations", tag: "YOUR DAILY OPERATIONS", title: "Your daily back office, within reach.", description: "Put the tools you open every day directly on your keyboard.", items: [["Your key", "Store admin", "Open store page", "store"], ["Your key", "Support", "Open support desk", "message"], ["Your key", "ERP / OMS", "Open management", "layout"], ["Your key", "Dashboard", "View metrics", "chart"]] },
    { name: "Content & work", tag: "MAKE ROOM FOR FOCUS", title: "Find fewer windows. Keep your focus.", description: "Reduce window hunting and repeated clicks so attention stays on the work.", items: [["Bound key", "Mail", "Open inbox", "mail"], ["Bound key", "Notion", "Open notes", "file"], ["Bound key", "ChatGPT", "Open app", "message"], ["Bound key", "Work folder", "Open directory", "folder"]] },
  ],
  features: [["app", "Open apps", "Put frequently used apps where your hand can find them.", "Implemented"], ["globe", "Open URLs", "Keep dashboards and docs one key away.", "Implemented"], ["terminal", "Run scripts", "Run local .sh scripts for development and daily work.", "Implemented"], ["command", "System shortcuts", "Bind copy, paste, and other keyboard shortcuts.", "Implemented"], ["switch", "Toggle apps", "Call an app forward and hide it when you are done.", "Coming soon"]],
  steps: [["01", "Connect your keyboard", "Use a standard keyboard or Macro Pad with recognizable keys."], ["02", "Choose an action", "Create an app, URL, script, or shortcut command in Blink."], ["03", "Record and bind a key", "Record a physical key, save the binding, and press it to go."]],
} as const;
export const toggleStates = [
  ["未启动", "启动并置前"],
  ["在后台", "切到前台"],
  ["在前台", "隐藏应用"],
];
export const keyMappings = [
  ["自定义按键", "ChatGPT"],
  ["自定义按键", "IDE"],
  ["自定义按键", "常用网页"],
  ["自定义按键", "本地脚本"],
];

export const productViews = [
  {
    id: "commands",
    label: "命令面板",
    images: [{ src: "/runtime-commands.png", alt: "Blink 命令面板中的用户命令列表" }],
    alt: "Blink 真实命令面板，展示用户命令、动作类型和按键绑定入口",
    caption: "当前 Blink Command Deck · 真实界面",
    title: "命令都在这里。",
    description: "查看自己创建的命令、动作来源与绑定状态，常用入口一目了然。",
    detail: "真实 Runtime 界面",
  },
  {
    id: "create",
    label: "创建命令",
    images: [
      {
        src: "/runtime-creator.png",
        alt: "Blink Creator 新增命令界面，展示动作类型、网址和命令名称",
      },
    ],
    alt: "Blink Creator 真实新增命令界面",
    caption: "当前 Creator · 真实新增命令状态",
    title: "选择动作，写下名称。",
    description: "Creator 集中呈现动作类型、目标内容和命令名称。一个命令对应一个明确动作。",
    detail: "真实 Creator UI",
  },
  {
    id: "binding",
    label: "绑定按键",
    images: [
      { src: "/runtime-binding-capture.png", alt: "Blink 等待用户按下实体键进行绑定" },
      { src: "/runtime-binding-done.png", alt: "Blink 完成绑定并显示 F10 keycap 结果" },
    ],
    alt: "Blink 实体键捕获与绑定完成的真实界面",
    caption: "真实绑定过程 · 捕获实体键 → 显示 keycap",
    title: "按下实体键，完成绑定。",
    description: "Blink 先进入捕获状态；收到实体键后保存绑定，并在命令行中显示对应 keycap。",
    detail: "真实 Runtime 绑定状态",
  },
] as const;

export const showcaseLabels = {
  eyebrow: "BLINK, FROM COMMAND TO KEY",
  group: "切换产品界面",
};

export const hardwareValues = [
  ["软件里修改", "保存后应用新动作"],
  ["动作留在软件侧", "尽量少改设备与固件"],
  ["普通设备也能用", "前提是系统能识别按键"],
] as const;

export const hardwareStories = [
  {
    id: "open-app",
    key: 1,
    title: "按一下，打开常用 App",
    action: "按键 1 → 打开 ChatGPT",
    icon: "message",
    status: "打开应用",
  },
  {
    id: "return-work",
    key: 2,
    title: "按一下，回到正在做的事",
    action: "按键 2 → 启动 VS Code",
    icon: "code",
    status: "进入工作",
  },
  {
    id: "toggle-app",
    key: 3,
    title: "按一下叫出，再按一次收起",
    action: "按键 3 → ChatGPT 显示 / 隐藏",
    icon: "switch",
    status: "即将支持 · App 切换",
  },
  {
    id: "clear-action",
    key: 2,
    title: "按一下，触发一个明确动作",
    action: "一个按键，对应一个独立结果",
    icon: "command",
    status: "更多动作",
    alternatives: ["打开链接", "执行快捷键", "运行本地脚本"],
  },
] as const;
