export const DOWNLOAD_URL_PLACEHOLDER = '#download';
export const SITE_URL = ''; // Set to the verified Sites URL before release.
export const copy = {
  title: 'Blink - 把任意按键变成快捷动作',
  description: 'Blink 是一款桌面快捷控制工具，将 App、URL、脚本和系统动作绑定到实体按键，一键启动、切换和执行。',
  email: 'lixinzhang0703@gmail.com',
  hero: { badge: '为你的 Mac，多一点顺手', title: ['把常用动作，', '交给一个按键。'], description: '将 App、URL、脚本和系统动作绑定到实体键盘。\n一键直达，少一点寻找，多一点专注。' },
  scenarios: [
    {name:'开发者',tag:'BUILD YOUR NEXT IDEA',title:'从灵感，到代码。少几个点击。',description:'为你的工作流准备一组专属按键。编辑器、终端和开发页面，各就各位。',items:[['F13','VS Code','打开编辑器','code'],['F14','Terminal','进入终端','terminal'],['F15','GitHub','查看代码仓库','github'],['F16','localhost','打开本地页面','globe']]},
    {name:'电商运营',tag:'YOUR DAILY OPERATIONS',title:'每天的高频后台，触手可及。',description:'不用再找收藏夹，把每天都会打开的工具直接放到键盘上。',items:[['F13','店铺后台','打开店铺页面','store'],['F14','客服系统','进入客服工作台','message'],['F15','ERP / OMS','打开管理后台','layout'],['F16','数据看板','查看经营数据','chart']]},
    {name:'内容与办公',tag:'MAKE ROOM FOR FOCUS',title:'少找一个窗口，多留一点心流。',description:'减少寻找窗口和重复点击，把注意力留给真正的工作。',items:[['F13','邮箱','打开收件箱','mail'],['F14','Notion','进入笔记空间','file'],['F15','ChatGPT','打开常用应用','message'],['F16','工作文件夹','打开本地目录','folder']]}
  ],
  features: [
    ['app','打开 App','把常用应用，放到顺手的位置。快速启动，直接进入。','已实现'],
    ['globe','打开 URL','后台、文档、固定网页。常用入口，不必再翻收藏夹。','已实现'],
    ['terminal','执行脚本','运行本地 .sh 脚本，为开发和日常工作少一次重复操作。','已实现'],
    ['command','系统快捷操作','绑定复制、粘贴等快捷键。需授予 macOS 辅助功能权限。','已实现'],
    ['switch','快速切换 App','需要时叫出，结束后收起。让窗口跟上你的节奏。','即将支持']
  ],
  steps:[['01','连接你的键盘','普通键盘或 Macro Pad，选择系统能够识别的按键。'],['02','选择一个动作','在 Blink 中创建 App、URL、脚本或快捷键命令。'],['03','录制并绑定按键','为命令录制实体按键，保存绑定。按一下，开始使用。']]
};

export const labels = {
  "brand": "Blink",
  "skip": "跳转到正文",
  "navFeatures": "功能",
  "navScenarios": "使用场景",
  "navHow": "如何使用",
  "download": "下载 Blink",
  "learn": "了解 Blink",
  "macFirst": "macOS 优先",
  "separator": "·",
  "early": "早期版本，下载即将开放",
  "windowDots": "● ● ●",
  "runtime": "Blink Runtime",
  "shotTag": "为专注而设计",
  "shotCaption": "来自当前 Runtime 的界面截图 · 展示状态为模拟数据",
  "physicalKeys": "实体按键，软件定义",
  "oneKey": "一个按键，一个动作",
  "noFirmware": "无需刷固件",
  "scenariosEyebrow": "MADE FOR YOUR EVERYDAY",
  "scenariosTitle": "你的工作流，",
  "scenariosTitleAccent": "就在键盘上。",
  "scenariosDescription": "为每天重复打开的工具，准备一排专属快捷键。",
  "scenarioNote": "配置示例 · 每个按键对应一个独立动作",
  "toggleEyebrow": "RIGHT HERE. THEN OUT OF THE WAY.",
  "soon": "即将支持",
  "togglePlatform": "macOS App 切换",
  "toggleTitle": "一键叫出，",
  "toggleTitleAccent": "再按一次收起。",
  "toggleDescription": "为常用 App 设置专属按键。需要时立即呼出，使用结束后一键隐藏。",
  "toggleStateNote": "根据应用真实状态决定下一步动作。",
  "toggleReleaseNote": "功能开发中，稳定版本确认后开放。",
  "toggleExample": "以 ChatGPT 为例",
  "toggleDiagram": "行为示意",
  "toggleKey": "F13",
  "toggleFooter": "随叫随到，也懂适时退场。",
  "keysEyebrow": "GIVE EVERY KEY A PURPOSE",
  "keysTitle": "那些闲着的按键，",
  "keysTitleAccent": "可以很有用。",
  "keysList": "F13、F14、F15、F16……",
  "keysDescription": "让少用的功能键，成为你的常用入口。",
  "keysNote": "映射示例 · 适用于系统可识别、Blink 可监听的按键",
  "featuresEyebrow": "SMALL KEY. MORE POSSIBILITIES.",
  "featuresTitle": "一个按键，",
  "featuresTitleAccent": "可以做更多。",
  "featuresDescription": "从打开应用到运行脚本，把重复的点击交给 Blink。",
  "firmwareEyebrow": "YOUR KEYBOARD. YOUR RULES.",
  "firmwareTitle": "不刷固件，",
  "firmwareTitleAccent": "直接定义键盘。",
  "firmwareLead": "键盘保持原样。",
  "firmwareLeadEnd": "改变的，是你使用它的方式。",
  "firmwareDescription": "按键定义保存在电脑端。更换动作，只需修改软件配置，无需重新烧录键盘，也不需要为映射安装厂商专用驱动。",
  "softwareConfig": "软件侧配置",
  "editAnytime": "随时调整动作",
  "keyboardTypes": "普通键盘 / Macro Pad",
  "firmwareNote": "设备需能向系统发送可识别按键。不同电脑需要各自配置，当前不提供账号同步。",
  "howEyebrow": "LESS SETUP. MORE DOING.",
  "howTitle": "简单三步，",
  "howTitleAccent": "让按键就位。",
  "downloadEyebrow": "ONE KEY. YOUR WAY.",
  "downloadTitle": "让你的键盘，",
  "downloadTitleAccent": "真正为你工作。",
  "tagline": "把常用动作，交给一个按键。",
  "downloadMac": "下载 Blink for macOS",
  "downloadSoon": "即将开放",
  "downloadNote": "正在准备首个公开下载版本。",
  "contactAuthor": "联系作者",
  "mac": "macOS",
  "macStatus": "优先支持",
  "windows": "Windows",
  "windowsStatus": "后续计划",
  "footerTagline": "一个按键，一个动作。",
  "product": "产品",
  "footerDownload": "下载",
  "support": "支持",
  "emailFeedback": "邮件反馈",
  "feedbackLine1": "如果新版本使用中遇到问题，",
  "feedbackLine2": "欢迎发送邮件反馈。",
  "copyright": "© 2026 Blink",
  "footerEnglish": "Designed for your everyday.",
  "downloadReady": "macOS 版本现已开放下载",
  "homeLabel": "Blink 首页",
  "navLabel": "主导航",
  "scenarioLabel": "选择使用场景",
  "screenshotAlt": "Blink Runtime 中文设置页，展示通用设置、运行状态和帮助反馈"
};
export const toggleStates = [["未启动","启动并置前"],["在后台","切到前台"],["在前台","隐藏应用"]];
export const keyMappings = [["F13","ChatGPT"],["F14","IDE"],["F15","常用网页"],["F16","本地脚本"]];
