mod binding; mod execution; mod profile; mod repository; mod tray; mod window;
use binding::BindingState; use profile::Profile; use repository::ProfileRepository; use serde::Serialize; use std::{collections::HashSet, path::PathBuf, sync::{Mutex, atomic::{AtomicBool, Ordering}}}; use tauri::{AppHandle, Emitter, Manager, State}; use tauri_plugin_global_shortcut::{GlobalShortcutExt, Shortcut, ShortcutState};
struct RuntimeCore { repository: ProfileRepository, bindings: BindingState, listener_status: String, binding_capture: bool, last_error: Option<String>, last_event: Option<String>, repository_file: PathBuf, binding_file: PathBuf }
type SharedRuntime = Mutex<RuntimeCore>;
pub(crate) struct AppLifecycle(pub AtomicBool);
#[derive(Serialize)] #[serde(rename_all="camelCase")] struct RuntimeProfileView { id:String,name:String,description:Option<String>,physical_input:Option<String>,icon_id:Option<String> }
#[derive(Serialize)] #[serde(rename_all="camelCase")] struct RuntimeSnapshot { profiles:Vec<RuntimeProfileView>, listener_status:String, last_error:Option<String>, last_event:Option<String> }
pub(crate) fn listener_status_label(status:&str)->&'static str { match status { "LISTENING"=>"● 正在监听", "PAUSED"=>"○ 已暂停", _=>"⚠ 需要处理" } }
fn ids(repository:&ProfileRepository)->HashSet<String>{repository.profiles.iter().map(|profile|profile.id.clone()).collect()}
fn set_status(app:&AppHandle,status:&str){ {let state=app.state::<SharedRuntime>(); state.lock().expect("runtime lock").listener_status=status.into();} tray::update(app,status); }
fn register_state(app:&AppHandle,state:&BindingState)->Result<(),String>{ let manager=app.global_shortcut(); manager.unregister_all().map_err(|e|e.to_string())?; for key in state.physical_to_profile.keys(){ manager.register(key.replace("META","SUPER").parse::<Shortcut>().map_err(|e|format!("无效物理按键 {key}: {e}"))?).map_err(|e|e.to_string())?; } Ok(()) }
fn refresh_listener(app:&AppHandle)->Result<(),String>{ let bindings={let state=app.state::<SharedRuntime>();let bindings=state.lock().expect("runtime lock").bindings.clone();bindings}; let count=bindings.physical_to_profile.len(); match register_state(app,&bindings){Ok(())=>{set_status(app,"LISTENING");publish_diagnostic(app,format!("已注册 {count} 个全局快捷键"),None);Ok(())},Err(e)=>{set_status(app,"ERROR");publish_diagnostic(app,"全局快捷键注册失败".into(),Some(e.clone()));Err(e)}} }
fn commit_bindings(app:&AppHandle,next:BindingState)->Result<(),String>{ let (previous,paused)={let state=app.state::<SharedRuntime>();let core=state.lock().expect("runtime lock");(core.bindings.clone(),core.listener_status=="PAUSED")}; if !paused { if let Err(error)=register_state(app,&next){let _=register_state(app,&previous);set_status(app,"ERROR");return Err(error);} } {let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");core.bindings=next;core.binding_capture=false;core.bindings.save(&core.binding_file)?;} if !paused{set_status(app,"LISTENING");}Ok(()) }
fn publish_diagnostic(app:&AppHandle,event:String,error:Option<String>){let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");let detail=error.clone();let log_file=core.repository_file.parent().map(|directory|directory.join("runtime-diagnostics.log"));core.last_event=Some(event.clone());core.last_error=error;drop(core);if let Some(log_file)=log_file{use std::io::Write;let line=match detail{Some(error)=>format!("{event} | {error}\n"),None=>format!("{event}\n")};let _=std::fs::OpenOptions::new().create(true).append(true).open(log_file).and_then(|mut file|file.write_all(line.as_bytes()));}let _=app.emit("runtime-diagnostic",());}
fn dispatch_profile(app:&AppHandle,id:&str){let executions={let state=app.state::<SharedRuntime>();let core=state.lock().expect("runtime lock");core.repository.find(id).and_then(|profile|profile.source_profile.bindings.iter().find(|binding|binding.id==profile.source_binding_id).map(|binding|binding.actions.iter().map(|action|action.executions.get(if cfg!(target_os="windows"){"windows"}else{"macos"}).cloned().ok_or_else(||"UNSUPPORTED_PLATFORM".into())).collect::<Vec<_>>()))};if let Some(executions)=executions{for execution in executions{if let Err(error)=execution.and_then(|value|execution::dispatch(&value)){publish_diagnostic(app,"已收到快捷键，但命令执行失败".into(),Some(error));return;}}publish_diagnostic(app,"已收到快捷键，命令执行完成".into(),None);}}
fn dispatch_physical_key(app:&AppHandle,shortcut:&Shortcut){let binding={let state=app.state::<SharedRuntime>();let core=state.lock().expect("runtime lock");core.bindings.physical_to_profile.iter().find_map(|(input,id)|input.replace("META","SUPER").parse::<Shortcut>().ok().filter(|value|value==shortcut).map(|_|(input.clone(),id.clone())))};if let Some((input,id))=binding{publish_diagnostic(app,format!("已收到全局快捷键 {input}"),None);dispatch_profile(app,&id)}}
fn pause_listener(app:&AppHandle)->Result<(),String>{app.global_shortcut().unregister_all().map_err(|e|e.to_string())?;set_status(app,"PAUSED");Ok(())}
pub(crate) fn toggle_listener(app:&AppHandle)->Result<(),String>{let paused={let state=app.state::<SharedRuntime>();let paused=state.lock().expect("runtime lock").listener_status=="PAUSED";paused};if paused{refresh_listener(app)}else{pause_listener(app)}}
pub(crate) fn shutdown_listener(app:&AppHandle){let _=app.global_shortcut().unregister_all();}
pub(crate) fn quit_keyflow(app:&AppHandle){app.state::<AppLifecycle>().0.store(true,Ordering::SeqCst);shutdown_listener(app);{let state=app.state::<SharedRuntime>();let core=state.lock().expect("runtime lock");let _=core.repository.save(&core.repository_file);let _=core.bindings.save(&core.binding_file);}app.exit(0);}
#[tauri::command] fn runtime_snapshot(core:State<SharedRuntime>)->RuntimeSnapshot{let core=core.lock().expect("runtime lock");RuntimeSnapshot{profiles:core.repository.profiles.iter().map(|profile|RuntimeProfileView{id:profile.id.clone(),name:profile.name.clone(),description:profile.description.clone(),physical_input:core.bindings.profile_to_physical.get(&profile.id).cloned(),icon_id:profile.icon_id.clone()}).collect(),listener_status:core.listener_status.clone(),last_error:core.last_error.clone(),last_event:core.last_event.clone()}}
#[tauri::command] fn toggle_listener_command(app:AppHandle)->Result<(),String>{toggle_listener(&app)}
#[tauri::command] fn quit_keyflow_command(app:AppHandle){quit_keyflow(&app)}
#[tauri::command] fn begin_binding_capture(app:AppHandle,profile_id:String)->Result<(),String>{ {let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");if core.repository.find(&profile_id).is_none(){return Err("RuntimeProfile 不存在".into());}if core.listener_status=="PAUSED"{return Err("监听已暂停，无法开始绑定".into());}core.binding_capture=true;} if let Err(error)=app.global_shortcut().unregister_all().map_err(|error|error.to_string()){let state=app.state::<SharedRuntime>();state.lock().expect("runtime lock").binding_capture=false;return Err(error);}publish_diagnostic(&app,"正在等待新的实体按键；已有绑定暂不执行".into(),None);Ok(())}
#[tauri::command] fn cancel_binding_capture(app:AppHandle)->Result<(),String>{ {let state=app.state::<SharedRuntime>();state.lock().expect("runtime lock").binding_capture=false;}refresh_listener(&app) }
fn import_profile(app:&AppHandle,profile:Profile)->Result<(),String>{let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");core.repository.insert_import(profile);core.repository.save(&core.repository_file)}
#[tauri::command] fn load_profile(app:AppHandle,path:String)->Result<(),String>{import_profile(&app,Profile::from_file(&path).map_err(|e|e.to_string())?)}
#[tauri::command] fn load_fixture_profile(app:AppHandle)->Result<(),String>{import_profile(&app,Profile::from_json(include_str!("../../../packages/keyflow-contract/fixtures/profile-v1.2.example.json")).map_err(|e|e.to_string())?)}
#[tauri::command] fn bind_key(app:AppHandle,profile_id:String,physical_key:String)->Result<(),String>{physical_key.replace("META","SUPER").parse::<Shortcut>().map_err(|e|format!("无效物理按键 {physical_key}: {e}"))?;let mut next={let state=app.state::<SharedRuntime>();let core=state.lock().expect("runtime lock");if core.repository.find(&profile_id).is_none(){return Err("RuntimeProfile 不存在".into());}core.bindings.clone()};next.bind_profile(&profile_id,&physical_key);debug_assert!(next.consistent());commit_bindings(&app,next)}
#[tauri::command] fn unbind_profile(app:AppHandle,profile_id:String)->Result<(),String>{let mut next={let state=app.state::<SharedRuntime>();let bindings=state.lock().expect("runtime lock").bindings.clone();bindings};next.unbind_profile(&profile_id);debug_assert!(next.consistent());commit_bindings(&app,next)}
#[tauri::command] fn rename_profile(app:AppHandle,profile_id:String,name:String)->Result<(),String>{let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");core.repository.rename(&profile_id,name)?;core.repository.save(&core.repository_file)}
#[tauri::command] fn set_profile_icon(app:AppHandle,profile_id:String,icon_id:String)->Result<(),String>{let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");core.repository.set_icon(&profile_id,icon_id)?;core.repository.save(&core.repository_file)}
#[tauri::command] fn delete_profile(app:AppHandle,profile_id:String)->Result<(),String>{unbind_profile(app.clone(),profile_id.clone())?;let state=app.state::<SharedRuntime>();let mut core=state.lock().expect("runtime lock");core.repository.delete(&profile_id).ok_or("RuntimeProfile 不存在")?;core.repository.save(&core.repository_file)}
fn main(){tauri::Builder::default().plugin(tauri_plugin_single_instance::init(|app,_,_|{let _=window::show_main_window(app);})).plugin(tauri_plugin_dialog::init()).plugin(tauri_plugin_global_shortcut::Builder::new().with_handler(|app,shortcut,event|if event.state()==ShortcutState::Pressed{dispatch_physical_key(app,shortcut)}).build()).setup(|app|{app.manage(AppLifecycle(AtomicBool::new(false)));let dir=app.path().app_data_dir()?;let repo_file=dir.join("profiles.json");let repository=ProfileRepository::load(&repo_file);let binding_file=dir.join("bindings.json");let bindings=BindingState::load(&binding_file,&ids(&repository));bindings.save(&binding_file)?;app.manage(Mutex::new(RuntimeCore{repository,bindings,listener_status:"LISTENING".into(),binding_capture:false,last_error:None,last_event:None,repository_file:repo_file,binding_file}));tray::install(app)?;refresh_listener(app.handle()).ok();#[cfg(not(debug_assertions))]if let Some(window)=app.get_webview_window("main"){window.hide()?;}Ok(())}).on_window_event(window::hide_on_close).invoke_handler(tauri::generate_handler![runtime_snapshot,toggle_listener_command,quit_keyflow_command,begin_binding_capture,cancel_binding_capture,load_profile,load_fixture_profile,bind_key,unbind_profile,rename_profile,set_profile_icon,delete_profile]).run(tauri::generate_context!()).expect("KeyFlow Runtime 启动失败");}
